### ISSUE TITLE
GoBGP backend does not work correctly if workloads across multiple hosts use IPs from the same /26

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calicoctl#1362] opened 2016-11-30 08:54 UTC
When using GoBGP, routes are not distributed correctly if workload IPs across different hosts are in the same /26.

```
calico@calico:~$ docker exec -it host1 sh
/ # ip route
default via 172.17.0.1 dev eth0 
172.17.0.0/16 dev eth0  proto kernel  scope link  src 172.17.0.2 
172.18.0.0/16 dev docker0  proto kernel  scope link  src 172.18.0.1 linkdown 
192.168.1.1 dev cali477fe74e236  scope link 
/ # ip route
/ # exit
calico@calico:~$ docker exec -it host2 sh
/ # ip route
default via 172.17.0.1 dev eth0 
172.17.0.0/16 dev eth0  proto kernel  scope link  src 172.17.0.3 
172.18.0.0/16 dev docker0  proto kernel  scope link  src 172.18.0.1 linkdown 
192.168.1.0/26 via 172.17.0.2 dev eth0 
192.168.1.2 dev cali40a01e5b70b  scope link 
/ # exit
calico@calico:~$ docker exec -it host3 sh
/ # ip route
default via 172.17.0.1 dev eth0 
172.17.0.0/16 dev eth0  proto kernel  scope link  src 172.17.0.4 
172.18.0.0/16 dev docker0  proto kernel  scope link  src 172.18.0.1 linkdown 
192.168.1.0/26 via 172.17.0.2 dev eth0 
192.168.1.3 dev calie3e75be44ef  scope link 
/ # exit
```

Should have had:

Host1 IP=172.17.0.2; Workload=192.168.1.1
Host2 IP=172.17.03; Workload=192.168.1.2
Host3 IP=172.17.03; Workload=192.168.1.3

But suspect the 192.168.1.0/26 route is mucking things up.

**Comment by ishidawataru** [comment] 2016-12-01 10:00
@robbrockbank Reproduced the issue. This is due to a lacking feature of `calico-bgp-daemon`.
I think I figured out what to implement, but I would like to hear your option before I proceed.
Below is my understanding. Could you check whether this is correct?

When the same /26 is assigned to multiple hosts, the prefix is only inserted to one place under etcd `/calico/ipam/v2/host`.

Here, we have two host running calico/node (backend `bird`), `host1`(ID: `41696fc7e17a`) and `host2`(ID:`287a548758f8`).

Below is the items under path `/calico/ipam/v2/host`

```
$ etcdctl ls -r /calico/ipam/v2/host
/calico/ipam/v2/host/41696fc7e17a
/calico/ipam/v2/host/41696fc7e17a/ipv6
/calico/ipam/v2/host/41696fc7e17a/ipv6/block
/calico/ipam/v2/host/41696fc7e17a/ipv4
/calico/ipam/v2/host/41696fc7e17a/ipv4/block
/calico/ipam/v2/host/41696fc7e17a/ipv4/block/192.168.1.0-26
/calico/ipam/v2/host/287a548758f8
/calico/ipam/v2/host/287a548758f8/ipv4
/calico/ipam/v2/host/287a548758f8/ipv4/block
/calico/ipam/v2/host/287a548758f8/ipv6
/calico/ipam/v2/host/287a548758f8/ipv6/block
```

When we see the RIB and FIB of two hosts, 

host1
```
$ docker exec -it host1 sh -c 'docker exec -it calico-node birdcl -s /var/run/calico/bird.ctl'
BIRD 1.5.0 ready.
bird> show route
0.0.0.0/0          via 172.17.0.1 on eth0 [kernel1 09:02:18] * (10)
192.168.1.0/26     blackhole [static1 09:02:26] * (200)
192.168.1.1/32     dev calie9ccb43ba0a [kernel1 09:02:26] * (10)
192.168.1.2/32     via 172.17.0.3 on eth0 [Global_172_17_0_3 09:02:37] * (100/0) [i]
172.18.0.0/16      dev docker0 [direct1 09:02:18] * (240)
172.17.0.0/16      dev eth0 [direct1 09:02:18] * (240)
```
```
$ docker exec -it host1 sh -c 'docker exec -it calico-node ip r'
default via 172.17.0.1 dev eth0
172.17.0.0/16 dev eth0  proto kernel  scope link  src 172.17.0.2
172.18.0.0/16 dev docker0  proto kernel  scope link  src 172.18.0.1 linkdown
blackhole 192.168.1.0/26  proto bird
192.168.1.1 dev calie9ccb43ba0a  scope link
192.168.1.2 via 172.17.0.3 dev eth0  proto bird
```

host2
```
$ docker exec -it host2 sh -c 'docker exec -it calico-node birdcl -s /var/run/calico/bird.ctl'
BIRD 1.5.0 ready.
bird> show route
0.0.0.0/0          via 172.17.0.1 on eth0 [kernel1 09:02:27] * (10)
192.168.1.0/26     via 172.17.0.2 on eth0 [Global_172_17_0_2 09:02:37] * (100/0) [i]
192.168.1.2/32     dev cali7ca8dbee878 [kernel1 09:02:28] * (10)
172.18.0.0/16      dev docker0 [direct1 09:02:26] * (240)
172.17.0.0/16      dev eth0 [direct1 09:02:26] * (240)
```
```
$ docker exec -it host2 sh -c 'docker exec -it calico-node ip r'
default via 172.17.0.1 dev eth0
172.17.0.0/16 dev eth0  proto kernel  scope link  src 172.17.0.3
172.18.0.0/16 dev docker0  proto kernel  scope link  src 172.18.0.1 linkdown
192.168.1.0/26 via 172.17.0.2 dev eth0  proto bird
192.168.1.2 dev cali7ca8dbee878  scope link
```

we can see 192.168.1.0/26 is 
only imported and advertised from `host1`. On `host1`, 192.168.1.1/32 is also
imported from kernel, but not advertised due to his export policy.

```
$ docker exec -it host1 sh -c 'docker exec -it calico-node cat /etc/calico/confd/config/bird_aggr.cfg'
# Generated by confd
# ------------- Static black hole addresses -------------
protocol static {
   route 192.168.1.0/26 blackhole;
}
# Aggregation of routes on this host; export the block, nothing beneath it.
function calico_aggr ()
{
  if ( net = 192.168.1.0/26 ) then { accept; }
  if ( net ~ 192.168.1.0/26 ) then { reject; }
}
```

However, as for `host2`, imported kernel route (192.168.1.2/32) is advertised.
This is also because of the export policy.

```
$ docker exec -it host2 sh -c 'docker exec -it calico-node cat /etc/calico/confd/config/bird_aggr.cfg'
# Generated by confd
# ------------- Static black hole addresses -------------
# No static routes configured.

# Aggregation of routes on this host; export the block, nothing beneath it.
function calico_aggr ()
{
}
```
Currently whole logic here (import kernel route, enforce export policy) is not implemented in `calico-bgp-daemon`. This is the reason why the issue is happening.

If my understanding is correct, I can implement the feature in `calico-bgp-daemon`.

**Comment by robbrockbank** [comment] 2016-12-01 23:38
@ishidawataru Yes, if I understand correctly the issue is that it isn't currently importing and re-exporting kernel routes.   I assume the current implementation just uses the aggregation block for routing?

**Comment by ishidawataru** [comment] 2016-12-02 03:41
@robbrockbank Thank you for the clarification. Yes, current implementation only uses the aggregation block. I'll try to fix this issue.

**Closed** 2017-03-02 22:45 UTC
Labels: kind/bug, priority/P3
