### ISSUE TITLE
First Calico re-launch after Kubernetes startup yields "Unable to remove filesystem" failure

### ISSUE THREAD

**Issue by DreadPirateShawn** [projectcalico/calicoctl#1006] opened 2016-06-01 18:27 UTC
We've run into a bug when we try to upgrade our Kubernetes hosts.

The following repro is performed on one of our Kubernetes master hosts. Our basic flow is that we shutdown Kubernetes services, reboot, then start all services.

(We do not shutdown Calico, since Calico is not meant to be stopped. Per devs on Calico slack, we should simply reboot the host when needed, and re-run "calicoctl node" to ensure startup / upgrade.)

However, this is what we see:
0) Prerequisite: Kubernetes master services are running, Calico is running
1) Stop Kubernetes master services
2) Reboot
3) Start Kubernetes master services
4) Start Calico, see error:

```
Traceback (most recent call last):
  File "<string>", line 145, in <module>
  File "calico_ctl/node.py", line 207, in node
  File "calico_ctl/node.py", line 302, in node_start
  File "calico_ctl/node.py", line 343, in _start_node_container_docker
  File "site-packages/docker/utils/decorators.py", line 21, in wrapped
  File "site-packages/docker/api/container.py", line 273, in remove_container
  File "site-packages/docker/client.py", line 146, in _raise_for_status
APIError: 500 Server Error: Internal Server Error ("Unable to remove filesystem for 3c39b14bbf990c19c4463626d1318379ffb0287522e1ad5e2b92fd9d0bd6d325: remove /var/lib/docker/containers/3c39b14bbf990c19c4463626d1318379ffb0287522e1ad5e2b92fd9d0bd6d325/shm: device or resource busy")
```

Note that the container ID matches the previously-running Calico container, and that no Calico containers remain running after the error.

Drilling deeper, I've learned that:
- The reboot can be replaced by a simple "service docker restart", and the issue still occurs -- in either case, the Calico container is still running after reboot / docker restart, since we never kill it.
- Idempotent Calico "calicoctl node" startup works without error when performed _before_ starting the Kubernetes master services
- Idempotent Calico "calicoctl node" startup works without error when performed again _after_ the failure repro

That is, this is another version of the repro:
0) Prerequisite: Kubernetes master services are running, Calico is running
1) Stop Kubernetes master services
2) Restart Docker (note that Calico container auto-restarts afterwards)
3) Start Calico, works fine, starts new container
4) Start Calico, works fine, starts new container
5) Start Kubernetes master services
6) Start Calico, see error, no Calico is running after the error
7) Start Calico, works fine, starts new container
8) Start Calico, works fine, starts new container

I've written a repro script to manifest this issue, bearing in mind that port IPs and hostnames will differ (and potentially ports), and that we have a VIP for our K8s HA master api server -- but this demonstrates the raw steps involved.

**Repro script:**
[Calico_issue1006_repro-script.txt](https://github.com/projectcalico/calico-containers/files/294151/Calico_issue1006_repro-script.txt)

**Output:**
[Calico_issue1006_repro-output.txt](https://github.com/projectcalico/calico-containers/files/294152/Calico_issue1006_repro-output.txt)

**Versions:**

```
$ docker -v
Docker version 1.10.3, build 20f81dd
$ /opt/calico/bin/calicoctl version
0.18.0
$ /opt/kubernetes/bin/hyperkube --version
Kubernetes v1.2.2
```

**Comment by DreadPirateShawn** [comment] 2016-06-01 18:37
Workarounds:

*Option 1) Be very strict about ordering*
~ Namely, for an upgrade, we must call "calicoctl node" after the reboot but before starting Kubernetes services, and be sure to never call "calicoctl node" again after the Kubernetes services are running.
~ *Risk:* This is a pretty brittle solution, and sacrifices idempotency. Calico crashes if anyone attempts to "re-start" Calico on a running system.

*Option 2) Handle the error*
~ Namely, upon calling "calicoctl node", check the output for this error, and re-call "calicoctl node" if this error is encountered.
~ *Benefit:* This solves any risk of someone attempting to "re-start" Calico on a running system, automatically recovers from the expected crash, without depending on brittle startup order and without carrying user interaction risks.

We'll be using option 2 (in case the "Risk" vs "Benefit" bullet points were too subtle :-P) until a more official workaround / fix is in place.

**Comment by caseydavenport** [comment] 2016-06-02 15:53
@DreadPirateShawn - thanks a lot for raising this - definitely something we want to fix.

I'm out of the office at MesosCon this week but will be investigating this once I'm back in the office.

**Comment by caseydavenport** [comment] 2016-06-06 22:35
So I tried a quick (but not exact since I'm running k8s using systemd rather than hyperkube) reproduction of the steps on my local cluster and didn't see the same error.

It seems that there are at least a few upstream Docker issues where people have been seeing this error message.

I took a look and found this issue: https://github.com/docker/docker/issues/5684#issuecomment-211897250

Which suggests Docker v1.11 has fixed a few cases where this error can occur.  It doesn't look _exactly_ like the case you describe, but it could be related.  Could you see if using Docker v1.11 fixes this issue?

**Comment by DreadPirateShawn** [comment] 2016-06-14 17:33
Sorry for the delay -- retested with `Docker version 1.11.1, build 5604cbe` and got the same error, same stacktrace, etc.

**Comment by caseydavenport** [comment] 2016-10-27 06:24
Sorry, it's been a while on this issue - @DreadPirateShawn is there any more recent status on this issue?

I've not been able to reproduce myself, and my feeling is that this is _probably_ an issue with Docker, but it's hard to say for sure.

**Comment by DreadPirateShawn** [comment] 2016-11-02 15:41
@caseydavenport No change -- same versions of everything, same behavior. I'm inclined to agree with your suspicion.

We attempted to upgrade to Docker 1.12 recently, but ultimately ran into docker/docker#27607 as a blocker issue, and we needed to roll back. At this point we're waiting for Docker 1.13 (pending soon) and revisiting.

**Comment by DreadPirateShawn** [comment] 2016-11-02 16:34
Actually, I found a stack with Docker 1.12 on it -- same error, same stacktrace, etc. `Docker version 1.12.2, build bb80604`

This might also be a Docker + Kernel combo issue -- we've seen those crop up more and more during our various adventures. We're on kernel `3.13.0-55-generic`.

**Comment by caseydavenport** [comment] 2017-01-20 00:20
I'm going to close this for now, since I've been unable to reproduce and I'm not convinced it's a Calico issue.

Please do poke me if it turns out there's evidence for something wrong on Calico's end.

**Closed by caseydavenport** 2017-01-20 00:20 UTC
Labels: integration/kubernetes, kind/bug, priority/P3
