### ISSUE TITLE
calicoctl node run command should be able to mount non default docker socket

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/calicoctl#1388] opened 2016-12-06 18:05 UTC
calicoctl node run only mounts `/var/run/docker.sock` by default

See https://github.com/projectcalico/libnetwork-plugin/issues/90#issuecomment-264939740 for details

**Comment by caseydavenport** [comment] 2017-08-01 21:08
Closing as a duplicate of https://github.com/projectcalico/calicoctl/issues/1404

**Closed by caseydavenport** 2017-08-01 21:08 UTC
Labels: area/calicoctl
