### ISSUE TITLE
Connecting a container to both a calico and bridge network doesn't work all the time

### ISSUE THREAD

**Issue by sdurrheimer** [projectcalico/calicoctl#1069] opened 2016-07-18 07:31 UTC
Hi there, using calico as docker libnetwork plugin, is it possible to connect a single container to both a calico network (with calico ipam driver) and a bridge network ?
The reason behind that is to be able to give internet connectivity to some containers without using a calico network with the default ipam driver which would give access to internet to all containers of this network.

Here are some tests I've been doing, 4 scenarios to be precise, some are working partially (connection to networks works but doesn't do the job), some failed instantly.

What I can say is that when connecting a container to a second network, docker reorganises networks connections alphabetically, so the first one of the ordered list will be the default route.
#### Partially working scenario n°1

```
$ docker network create \
    --driver calico \
    --ipam-driver calico \
    --subnet 10.99.0.0/16 \
    abc

$ docker network create \
    --driver bridge \
    --subnet 172.99.0.0/16 \
    xyz
```

```
$ docker run --rm -t -i --net abc --name endpoint-X debian:8

$ docker network connect xyz endpoint-X
```

```
root@77ebb1c125ec:/# ip route
default via 172.25.14.11 dev cali0 
172.25.14.11 dev cali0  scope link 
172.99.0.0/16 dev eth1  proto kernel  scope link  src 172.99.0.2
```

**=> Connection to both networks works but bridge is not the default route so no internet connectivity. Pinging a second container on the calico network works.**
#### Failed scenario n°1

```
$ docker network create \
    --driver calico \
    --ipam-driver calico \
    --subnet 10.99.0.0/16 \
    xyz

$ docker network create \
    --driver bridge \
    --subnet 172.99.0.0/16 \
    abc
```

```
$ docker run --rm -t -i --net xyz --name endpoint-X debian:8

$ docker network connect abc endpoint-X

$ docker network connect abc endpoint-X
Error response from daemon: driver failed revoking external connectivity on endpoint endpoint-X (4626e385eaf02695186714703648906143a06bf39188f99c5cdb0533bdbf4b82): network not found: 48d45ea160c2a354d2e10269caae5d443c452fb1d6c1bbbcafc6ba413ca79bc0
```

```
root@d3377b38b94b:/# ip route
default via 172.99.0.1 dev eth1 
172.25.14.11 dev cali0  scope link 
172.99.0.0/16 dev eth1  proto kernel  scope link  src 172.99.0.2
```

**=> Here we can see that the connection to the bridge network returns a error. The container has two routes, one for each network. The bridge is the default one, but if we inspect the bridge network, the container is not part of his containers list.
Internet connectivity ok, calico connectivity not ok.**

```
$ docker network inspect abc
[
    {
        "Name": "abc",
        "Id": "a6aef45b45d6403d4e61cd3765f8d2c3b511ea7044feb40030e7dd9a4e6758f6",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.99.0.0/16"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]

$ docker network inspect xyz
[
    {
        "Name": "xyz",
        "Id": "48d45ea160c2a354d2e10269caae5d443c452fb1d6c1bbbcafc6ba413ca79bc0",
        "Scope": "global",
        "Driver": "calico",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "calico",
            "Options": {},
            "Config": [
                {
                    "Subnet": "10.99.0.0/16"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "d3377b38b94b0f4a306e8e4c49a0015ce41f9f6806b67f1c518c8acda3979110": {
                "Name": "endpoint-X",
                "EndpointID": "4626e385eaf02695186714703648906143a06bf39188f99c5cdb0533bdbf4b82",
                "MacAddress": "ee:ee:ee:ee:ee:ee",
                "IPv4Address": "10.99.0.1/32",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```
#### Partially working scenario n°2

```
$ docker network create \
    --driver calico \
    --ipam-driver calico \
    --subnet 10.99.0.0/16 \
    xyz

$ docker network create \
    --driver bridge \
    --subnet 172.99.0.0/16 \
    abc
```

```
$ docker run --rm -t -i --net abc --name endpoint-X debian:8

$ docker network connect xyz endpoint-X
```

```
root@a18c9946e724:/# ip route
default via 172.99.0.1 dev eth0 
172.25.14.11 dev cali1  scope link 
172.99.0.0/16 dev eth0  proto kernel  scope link  src 172.99.0.2
```

**=> Connection to both networks works. Internet connectivity ok, but pinging a second container on the calico network doesn't work.**
#### Partially working scenario n°3

```
$ docker network create \
    --driver calico \
    --ipam-driver calico \
    --subnet 10.99.0.0/16 \
    abc

$ docker network create \
    --driver bridge \
    --subnet 172.99.0.0/16 \
    xyz
```

```
$ docker run --rm -t -i --net xyz --name endpoint-X debian:8

$ docker network connect abc endpoint-X
```

```
root@356cd0d7ed98:/# ip route
default via 172.25.14.11 dev cali1 
172.25.14.11 dev cali1  scope link 
172.99.0.0/16 dev eth0  proto kernel  scope link  src 172.99.0.2
```

**=> Connection to both networks works but bridge is not the default route so no internet connectivity. Pinging a second container on the calico network works.**

**Comment by fasaxc** [comment] 2016-07-18 08:23
Thanks for mapping this all out for us.  I've asked one of our container experts to take a look.  I'm wondering if this is a regression with some changes in Docker, for example.  What versions of Calico and Docker are you using?

**Comment by sdurrheimer** [comment] 2016-07-18 08:25
Docker: 1.11.2
Calico node: v0.20.0
Calico libnetwork: v0.8.0

**Comment by matthewdupre** [comment] 2016-07-27 18:00
@sdurrheimer I'd probably advise avoiding using two networks: they won't play nicely because of default route conflicts, as you've identified.

I can think of a couple of ways to only give some containers internet access without needing additional veths (which only causes problems):

1. Use --nat-outgoing on the pool, but use security policy to ban connections from the non-internet connected containers to/from the internet (e.g. say pool is 192.168.0.0/16; have an outgoing and incoming rule that allows to/from 192.168.0.0/16, followed by a drop all).  Policy applies before the nat, so they won't be able to reach the internet.

2. Use multiple Calico pools; one of which has --nat-outgoing, and place containers on them accordingly.

Would one of these work for you?

**Comment by robbrockbank** [comment] 2016-08-04 22:00
Hi @sdurrheimer, As Matt mentions the default route conflicts prevent multiple calico networks being connected to a single container.   This is a known limitation of our libnetwork integration and isn't something we can easily workaround.

Perhaps you could outline what behavior you are trying to achieve and which aspects of Calico that you are interested in (IP per container or our isolation model).  It might be that we can work out a particular deployment scenario that will give you what you need.

**Comment by tmjd** [comment] 2017-02-15 16:43
There have been no updates on this issue for a while so I'm closing it.  If you believe this should still be open please feel free to reopen.

**Closed by tmjd** 2017-02-15 16:43 UTC
Labels: kind/support
