### ISSUE TITLE
Implement adjustable host affinity pool sizes

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calicoctl#1384] opened 2016-12-05 19:09 UTC
By default, calico assigns a /26 block to each host from the larger configured pools.

This imposes a minimum pool size of /25.

We should allow the /26 to be configurable so users can sacrifice speed optimization to allow for smaller pool sizes, all the way up to /32.

**Comment by caseydavenport** [comment] 2018-03-09 07:14
Closing as a duplicate of https://github.com/projectcalico/libcalico-go/issues/761

**Closed by caseydavenport** 2018-03-09 07:14 UTC
Labels: Spec work needed, kind/enhancement, priority/P3
