### ISSUE TITLE
calicoctl node run should pass through all Calico env vars

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calicoctl#1403] opened 2016-12-09 17:48 UTC
e.g. it should pass through all environment variables prefixed with `CALICO_`

This allows is to easily add flags to components e.g. libnetwork-plugin or felix, and have a way for users to configure them

**Comment by gunjan5** [comment] 2017-03-01 23:12
Duplicate of https://github.com/projectcalico/calicoctl/issues/1501

**Closed by gunjan5** 2017-03-01 23:12 UTC
Labels: kind/enhancement
