### ISSUE TITLE
Proposal: Ability to use static IPs configured per ContainerID

### ISSUE THREAD

**Issue by zefciu** [projectcalico/calicoctl#1050] opened 2016-07-08 13:02 UTC
We want to deploy on kubernetes some applications that require the IP to be static (e.g. they use IP as prefixes in queues). k8s doesn't guarantee however that the Pod IP wouldn't change during its lifecycle.

My idea is to implement the logic of static IPs on the level of calico CNI plugin. It would be configured with a mapping of ContainerID -> IP. If a containerID is found in this mapping it would use static IP feature in calico. Otherwise it would act as currently.

What do you think about the above idea? Is this a logic that would belong to the CNI plugin? Or should it be implemented in calico itself?

**Comment by lxpollitt** [comment] 2016-07-08 18:44
cc @caseydavenport since I know he's thought about this a bit in the past.

Is ContainerID guaranteed to never change?  Would a pod annotation be more desirable mechanism in terms of usability?  (I'm not sure which is the easier to implement, but that's a a separate question.)

**Comment by caseydavenport** [comment] 2016-07-08 22:19
Yep, I've thought a little about this in the past.  We haven't done this just yet because we expected the new PetSet resource to cover many of the use cases.  However, I think PetSet doesn't @zefciu's use-case because the actual value of the IP address is important.

The containerID for a given pod will be different each time it is started, so I don't think we can rely on that.  Similarly, we can't rely on the `namespace/podname` since the pod name can be different upon re-scheduling.

I think an annotation is the closest thing here, so you could do something like this:

```
kind: Pod
apiVersion: v1
metadata:
  name: mypod
  annotations:
    "projectcalico.org/podIP": "192.168.5.5"
spec:
  ...
```

**Comment by caseydavenport** [comment] 2016-07-08 22:22
I do have a concern that there would be a number of edge cases we'd need to think about here.  First thoughts being:
- What if the address has already been allocated to another pod?
- What if multiple pods request the same IP via the annotation (e.g a ReplicaSet with 3 replicas)
- Currently, if a host crashes, the endpoints and IP allocations will not be cleaned up.  Do we prevent the re-scheduled pod from coming up with the same IP address?  Or do we allow it and risk having multiple pods with the same IP (not sure how k8s would / could handle that)

That's not to say the above questions are insurmountable, but we'd need to think about the right resolution.

**Comment by caseydavenport** [comment] 2017-01-20 00:22
Closing this as a duplicate of the more active discussion here: https://github.com/projectcalico/cni-plugin/issues/213

**Closed by caseydavenport** 2017-01-20 00:22 UTC
Labels: integration/kubernetes, kind/enhancement
