### ISSUE TITLE
Calico does not clean up etcd data when node removed

### ISSUE THREAD

**Issue by mozhuli** [projectcalico/calicoctl#1663] opened 2017-06-09 08:53 UTC
when a node removed, and with a different hostname and same ip added to calico, which caused error: `Calico node(***) already using the IPv4 address ***`. because calico does not clean up etcd data when node removed.
## Expected Behavior

when a node removed, the calico node data in the etcd  should be clean up. Is there some way to clean up calico node data using calicoctl manually, or configure parameters allowing calico clean up data  automatically when calico removed ? 
## Steps to Reproduce (for bugs)

1.set the node not available scheduling
2.kubelet delete node ***
3.change the hostname
4.kubeadm join --token $token ${master_ip}

## Your Environment

* calicoctl version (e.g. `calicoctl version`):
```
[root@10 ~]# ./calicoctl version
Version:      v1.1.3
Build date:   
Git commit:   e8a457d
```
* calico/node version (e.g. `docker run --rm calico/node versions`):v1.1.3
* Orchestrator type and version (e.g. kubernetes, mesos, rkt):k8s
* Operating System and version:Centos7.0
* Link to your project (optional):

**Comment by tmjd** [comment] 2017-06-09 13:36
What you are seeing is the expected behavior and manual removal is needed. Check out this page http://docs.projectcalico.org/v2.2/usage/decommissioning-a-node for how to remove a node.  Make sure the prerequisites are satisfied before issuing the commands listed on that page.

There currently is no auto-remove feature in Calico though we welcome feature requests and community contributions.

Since this is known and expected behavior I'm going to close this issue.  Thanks for using Calico.

**Closed by tmjd** 2017-06-09 13:36 UTC
Labels: kind/support
