### ISSUE TITLE
confd ERROR with bird (calico-node:v1.0.0-beta) Unable to open included file /etc/calico/confd/config/bird6_aggr.cfg

### ISSUE THREAD

**Issue by javaboyuk** [projectcalico/calicoctl#1328] opened 2016-11-23 12:33 UTC
I am getting this ERROR in /var/log/calico/confd:

> 
2016-11-23T11:47:44Z master-1 confd[89]: DEBUG Target config /etc/calico/confd/config/bird.cfg in sync
2016-11-23T11:47:44Z master-1 confd[89]: DEBUG Comparing candidate config to /etc/calico/confd/config/bird6.cfg
2016-11-23T11:47:44Z master-1 confd[89]: INFO Target config /etc/calico/confd/config/bird6.cfg out of sync
2016-11-23T11:47:44Z master-1 confd[89]: DEBUG Running bird6 -p -c /etc/calico/confd/config/.bird6.cfg161392533
2016-11-23T11:47:44Z master-1 confd[89]: ERROR "bird: /etc/calico/confd/config/.bird6.cfg161392533, line 2: Unable to open included file /etc/calico/confd/config/bird6_aggr.cfg: No such file or directory\n"
2016-11-23T11:47:44Z master-1 confd[89]: ERROR Config check failed: exit status 1
2016-11-23T11:47:46Z master-1 confd[89]: ERROR 100: Key not found (/calico/ipam/v2/host/master-1/ipv6) [8185]
This last line then just repeats continuously.

This is my setup which is not working.
==========================
Using v1.0.0-beta
(calico, calico-ipam 1.5.1 , cni 0.3.0, kube 1.4.6)
This is my calico config:
export ETCD_ENDPOINTS="http://192.168.0.31:2379,http://192.168.0.32:2379,http://192.168.0.33:2379"
RT_CALICO_NETWORK="10.3.0.0/16"
cat > /etc/calico/calico.env <<EOF
ETCD_ENDPOINTS="${ETCD_ENDPOINTS}"
ETCD_CA_FILE=""
ETCD_CERT_FILE=""
ETCD_KEY_FILE=""
CALICO_HOSTNAME=""
CALICO_NO_DEFAULT_POOLS="true"
RT_CALICO_NETWORK="${RT_CALICO_NETWORK}"
CALICO_IP=""
CALICO_IP6=""
CALICO_AS=""
CALICO_LIBNETWORK_ENABLED=true
CALICO_NETWORKING_BACKEND=bird
EOF

cat > /etc/calico/ippool.yaml <<EOF
      apiVersion: v1
      kind: ipPool
      metadata:
        cidr: ${RT_CALICO_NETWORK}
      spec:
        nat-outgoing: true
EOF
cat /etc/calico/ippool.yaml

cat > /usr/lib/systemd/system/calico-node.service <<EOF
[Unit]
Description=calico-node
After=docker.service
Requires=docker.service

[Service]
EnvironmentFile=/etc/calico/calico.env
ExecStartPre=-/usr/bin/docker rm -f calico-node
ExecStartPre=/usr/bin/printenv

#ExecStartPre=/opt/bin/calicoctl create -f /etc/calico/ippool.yaml
#ExecStart=/usr/local/bin/calicoctl node --detach=false

ExecStart=/usr/bin/docker run --net=host --privileged \
 --name=calico-node \
 -e HOSTNAME=\${HOSTNAME} \
 -e IP=\${CALICO_IP} \
 -e IP6=\${CALICO_IP6} \
 -e CALICO_NETWORKING_BACKEND=\${CALICO_NETWORKING_BACKEND} \
 -e AS=\${CALICO_AS} \
 -e NO_DEFAULT_POOLS=\${CALICO_NO_DEFAULT_POOLS} \
 -e CALICO_LIBNETWORK_ENABLED=\${CALICO_LIBNETWORK_ENABLED} \
 -e ETCD_ENDPOINTS=http://192.168.0.31:2379,http://192.168.0.32:2379,http://192.168.0.33:2379 \
 -e ETCD_CA_CERT_FILE=\${ETCD_CA_CERT_FILE} \
 -e ETCD_CERT_FILE=\${ETCD_CERT_FILE} \
 -e ETCD_KEY_FILE=\${ETCD_KEY_FILE} \
 -v /var/log/calico:/var/log/calico \
 -v /run/docker/plugins:/run/docker/plugins \
 -v /var/run/docker.sock:/var/run/docker.sock \
 -v /lib/modules:/lib/modules \
 -v /var/run/calico:/var/run/calico \
 calico/node:v1.0.0-beta

ExecStop=-/usr/bin/docker stop calico-node

[Install]
WantedBy=multi-user.target
EOF

cat > /etc/kubernetes/cni/net.d/10-calico.conf <<EOF
{
    "name": "calico-k8s-network",
    "type": "calico",
    "etcd_endpoints": "${ETCD_ENDPOINTS}",
    "log_level": "info",
    "kubernetes": {
        "k8s_api_root": "http://192.168.0.21:8080"
    },
    "ipam": {
        "type": "calico-ipam"
    },
    "policy": {
        "type": "k8s"
    }
}
EOF

**Comment by caseydavenport** [comment] 2016-11-23 22:47
@javaboyuk thanks for raising!

Note that it's Thanksgiving in the US the next couple of days, so a lot of us won't be doing much work in that time.

**Comment by caseydavenport** [comment] 2016-12-08 07:21
> (/calico/ipam/v2/host/master-1/ipv6

This looks like it could be a duplicate of https://github.com/projectcalico/calico-containers/issues/1340

Looks like something isn't writing out the key that it should be.  AFAICT that should be the IPAM code, but I feel like I'm missing something.  Once again, @robbrockbank?

**Comment by tmjd** [comment] 2017-03-01 20:34
@javaboyuk, is this still an issue for you?  If so could you try it again with the v1.0.2 release or the release candidate that is out, v1.1.0-rc6.  Thanks

**Comment by tmjd** [comment] 2017-03-16 07:03
Closing for now. @javaboyuk if this is still an issue for you please reopen and if possible retest with a newer version and let us know the results.  Thanks

**Closed by tmjd** 2017-03-16 07:03 UTC
Labels: kind/support
